In [1]:
import numpy as np
import pandas as pd

In [2]:
#abro el csv con pandas
movies= pd.read_csv('../Datos/movies_dataset.csv')
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

C:\Users\clari\AppData\Local\Temp\ipykernel_11128\3357341811.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies= pd.read_csv('../Datos/movies_dataset.csv')

In [3]:
#selecciona la columna y la convierto en un diccionario con el fin de prepararla para el siguiente paso
nombres= movies['belongs_to_collection']
nombres=dict(nombres)

In [4]:
# Busco iterar toda la serie, verificar que hay diccionario para tomar el valor de la clave 'name', contemplando los njulos
import json
import pandas as pd

def obtener_nombres(series):
    for nombre_dict_str in series:
        if pd.isnull(nombre_dict_str):
            yield None
        else:
            nombre_json = str(nombre_dict_str).replace("'", '"')
            try:
                nombre_dict = json.loads(nombre_json)
                if isinstance(nombre_dict, dict):  # Verificar que sea un diccionario
                    nombre = nombre_dict.get('name')
                    if nombre:
                        yield nombre
            except json.JSONDecodeError:
                pass

nombres = obtener_nombres(movies['belongs_to_collection'])

#guardo los datos en la lista collection
collection = []
for nombre in nombres:
   collection.append(nombre)

collection

['Toy Story Collection',
 None,
 'Grumpy Old Men Collection',
 None,
 'Father of the Bride Collection',
 None,
 None,
 None,
 None,
 'James Bond Collection',
 None,
 None,
 'Balto Collection',
 None,
 None,
 None,
 None,
 None,
 'Ace Ventura Collection',
 None,
 'Chili Palmer Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Babe Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Mortal Kombat Collection',
 None,
 None,
 None,
 'Pocahontas Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Lawnmower Man Collection',
 None,
 None,
 'Friday Collection',
 'From Dusk Till Dawn Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Muppet Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Neverending Story Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Bad Boys Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Batman Collection',
 None,
 None,
 'Brooklyn Cigar Store Collection',
 None,
 None,
 None,
 None,
 None,
 'Mexico Trilogy',
 None,
 'Die Hard Collection',
 'Teenage Apocalypse Trilogy',
 None,
 None,
 'Free Willy Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Power Rangers Collection',
 None,
 None,
 None,
 'Síť (kolekce)',
 None,
 None,
 None,
 None,
 None,
 None,
 'Showgirls Collection',
 'Brooklyn Cigar Store Collection',
 None,
 'Species Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Under Siege Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Burnt by the Sun Trilogy',
 None,
 'Before... Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 'Clerks Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Dumb and Dumber Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'A Goofy Movie Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Vampire Chronicles',
 None,
 None,
 None,
 None,
 None,
 None,
 'Star Wars Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Poison Ivy Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Three Colors Collection',
 'Three Colors Collection',
 'Three Colors Collection',
 None,
 None,
 None,
 None,
 'Swan Princess Series',
 None,
 None,
 None,
 'The Santa Clause Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Tales from the Crypt Collection',
 'Star Trek: The Next Generation Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Ace Ventura Collection',
 None,
 None,
 None,
 None,
 'The Jack Ryan Collection',
 None,
 None,
 None,
 'The Crow Collection',
 None,
 'The Flintstones (Live-Action) Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Lion King Collection',
 None,
 'A Nightmare on Elm Street Collection',
 'The Mask Collection',
 None,
 None,
 'Naked Gun Collection',
 None,
 None,
 None,
 None,
 None,
 'Speed Collection',
 None,
 'Timecop Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Street Fighter',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Highlander Collection',
 None,
 None,
 None,
 None,
 'Addams Family Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Beverly Hills Cop Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'City Slickers Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Endless Summer Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Free Willy Collection',
 None,
 'The Fugitive / U.S. Marshals Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 'Hard Target Collection',
 None,
 'Hot Shots! Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Jurassic Park Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Karate Kid Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'RoboCop Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Secret Garden Collection',
 None,
 'The Shadow Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Blade Runner Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Home Alone Collection',
 None,
 'Aladdin Collection',
 'The Terminator Collection',
 None,
 None,
 'Batman Collection',
 'The Hannibal Lecter Anthology',
 None,
 'Beauty and the Beast Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Candyman Collection',
 None,
 None,
 'Heavy Metal Collection',
 'Hellraiser Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'All Dogs Go to Heaven Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Mission: Impossible Collection',
 None,
 None,
 None,
 None,
 'DragonHeart Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Bloodsport Collection',
 'The Apu Collection',
 'The Apu Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Lemmy Caution Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Visitors Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Ghost in the Shell Collection',
 None,
 None,
 None,
 'Wallace & Gromit Collection',
 None,
 None,
 'The Arrival Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Trainspotting Collection',
 None,
 'Independence Day Collection',
 None,
 None,
 'The Hunchback of Notre Dame Collection',
 None,
 None,
 None,
 None,
 'The Nutty Professor Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Crow Collection',
 None,
 None,
 'Tales from the Crypt Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 'Escape From ... Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Godfather Collection',
 None,
 'Police Story Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Police Story Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Land Before Time Collection',
 None,
 None,
 'Halloween Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Space Odyssey Series',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Thin Man Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Living Dead Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Mighty Ducks Collection',
 None,
 'Witch Mountain Collection',
 'Herbie Collection',
 'Herbie Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Cinderella Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'The Fox and the Hound Collection',
 'Freeway Collection',
 None,
 'Die Hard Collection',
 'The Lawnmower Man Collection',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [5]:
# Agregar el DataFrame collection al DataFrame existente
df_collection= pd.DataFrame(collection, columns=['collection'])
movies = pd.concat([movies, df_collection], axis=1)
movies.head(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,collection
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,None
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,None
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection

In [6]:
#en cada fila de genres aplico la funcion
movie_genres = movies['genres'].apply(lambda x: [d['name'] for d in eval(x)] if pd.notnull(x) else [])
movies['genres']= movie_genres

In [8]:
#expresion regular para extraer los name referidos a los paises
movies['production_countries']= movies['production_countries'].str.extract(r"'name': '([^']*)'")

In [10]:
movies['production_companies']=movies['production_companies'].str.extract(r"'name': '([^']*)'")

In [11]:
movies["spoken_languages"]=movies["spoken_languages"].str.extract(r"'name': '([^']*)'")

In [12]:
#b)Los valores nulos de los campos revenue, budget deben ser rellenados por el número 0
movies['revenue'].fillna(0,inplace=True)
movies['budget'].fillna(0,inplace=True)

In [13]:
#c) Eliminar valores nulos en release_date
movies= movies.dropna(subset=['release_date'])
movies['release_date'].isnull().sum()

0

In [14]:
#d) De haber fechas, deberá tener el formato AAAA-mm-dd, además deberá crear la columna release_yeardonde extraerán el año de la fecha de estreno.
#hay algunos formatos bien, pero pasamos to_datetime para igual todos los datos
movies['release_date'] = pd.to_datetime(movies['release_date'], errors='coerce')
movies['release_date'] = pd.to_datetime(movies['release_date']).dt.strftime('%Y-%m-%d')#formato solicitado

In [15]:
#extraigo el año de release_date y lo paso como un DF
año = movies['release_date'].str.slice(0, 4)
año= list(año)
df_año= pd.DataFrame(año, columns=['release_year'])  # 45376 filas

In [16]:
#hago lo mismo con release_date. Para luego sumarlo como una nueva columna modificada
date= movies['release_date']
date= list(date)
df_date= pd.DataFrame(date, columns=['release_date'])
df_date= df_date.dropna() #45376 filas

In [17]:
#Al comprobar que tiene la misma cantidad de filas y no hay nulos. Elimino el release_date.
movies.drop(columns=['release_date'], inplace=True)
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'revenue', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count',
       'collection'],
      dtype='object')

In [18]:
#Ahora concateno al DF original, las nuevas columnas
movies = pd.concat([movies, df_date, df_año], axis=1)

In [19]:
#e)Cree la columna con el retorno de inversión, llame return con los campos revenuey budget, dividiendo estas dos últimas revenue / budget, cuando no haya datos disponibles para calcularlo, deberá tomar el valor 0.
#me tira error! debo convertir los datos a float
retorno = ((pd.to_numeric(movies['revenue'], errors='coerce')) /  (pd.to_numeric(movies['budget'], errors='coerce')))
retorno = pd.DataFrame(retorno, columns=['return'])
retorno.fillna(0, inplace=True)
retorno = retorno.replace(np.inf,0)
retorno

          return
0      12.451801
1       4.043035
2       0.000000
3       5.090760
4       0.000000
...          ...
44978   0.000000
45070   0.000000
45148   0.000000
45203   0.000000
45338   0.000000

[45464 rows x 1 columns]

In [20]:
movies = pd.concat([movies, retorno], axis=1)
movies.head(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,status,tagline,title,video,vote_average,vote_count,collection,release_date,release_year,return
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection,1995-10-30,1995,12.451801
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,None,1995-12-15,1995,4.043035
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection,1995-12-22,1995,0.000000
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,None,1995-12-22,1995,5.090760
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection,1995-02-10,1995,0.000000

In [21]:

# Contar los valores NaN en cada fila
num_nan = movies.isnull().sum(axis=1)

# Filtro y elimino las filas que tienen más de 15 NaN (15, porque conclui que con menos puede igual ser relevante )
movies = movies.dropna(thresh=movies.shape[1]-15)

movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,status,tagline,title,video,vote_average,vote_count,collection,release_date,release_year,return
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection,1995-10-30,1995,12.451801
1,False,NaN,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,None,1995-12-15,1995,4.043035
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection,1995-12-22,1995,0.000000
3,False,NaN,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,None,1995-12-22,1995,5.090760
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection,1995-02-10,1995,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45460,False,NaN,0,"[Drama, Action, Romance]",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,Released,NaN,Robin Hood,False,5.7,26.0,NaN,NaN,NaN,0.000000
45462,False,NaN,0,[Drama],NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,Released,NaN,Century of Birthing,False,9.0,3.0,NaN,NaN,NaN,0.000000
45463,False,NaN,0,"[Action, Drama, Thriller]",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,Released,A deadly game of wits.,Betrayal,False,3.8,6.0,NaN,NaN,NaN,0.000000
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,Released,NaN,Satan Triumphant,False,0.0,0.0,NaN,NaN,NaN,0.000000
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,Released,NaN,Queerama,False,0.0,0.0,NaN,NaN,NaN,0.000000

In [22]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'revenue', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count',
       'collection', 'release_date', 'release_year', 'return'],
      dtype='object')

In [24]:
#f) Eliminar las columnas que no se utilizarán, video, imdb_id, adult, original_title, poster_pathy homepage, status, tagline(elimino belong_to_collection ya que esta desanidado y e creado una nueva columna)
movies.drop(columns=['video','imdb_id','adult','original_title','poster_path', 'homepage','belongs_to_collection','status','tagline'], inplace=True)
movies.columns

Index(['budget', 'genres', 'id', 'original_language', 'overview', 'popularity',
       'production_companies', 'production_countries', 'revenue', 'runtime',
       'spoken_languages', 'title', 'vote_average', 'vote_count', 'collection',
       'release_date', 'release_year', 'return'],
      dtype='object')

Extraigo mes y dia de release_date para utilizar en las funciones solicitadas

In [25]:
movies = movies.dropna(subset=['release_date'])
movies['release_date'] = pd.to_datetime(movies['release_date'])
df_mes = pd.DataFrame({'release_month': movies['release_date'].dt.month})

C:\Users\clari\AppData\Local\Temp\ipykernel_11128\1286447000.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['release_date'] = pd.to_datetime(movies['release_date'])

In [26]:
movies = pd.concat([movies, df_mes], axis=1)
movies['release_year']= movies['release_year'].astype(int)

In [27]:
df_mes = df_mes.assign(release_day=movies['release_date'].dt.day)
dias = df_mes['release_day']
df_dias= pd.DataFrame(dias)

In [28]:
movies = pd.concat([movies, df_dias], axis=1)

In [30]:
movies.to_csv('movies_limpio.csv')